### ISSUE TITLE
Docusaurus 3 compatibility

### ISSUE THREAD

**Issue by darkbasic** [pradel/docusaurus-plugin-fathom#1]
I've just upgraded accounts.js to docusaurus 3 and I get the following warning:
```
➤ YN0060: │ @docusaurus/core is listed by your project with version 3.0.0, which doesn't satisfy what docusaurus-plugin-fathom (p98467) requests (^2.0.0).
```

Probably it does still work, but it's worth checking and eventually bumping the peerdeps range.

**Comment by pradel** [comment]
@darkbasic just published v1.2.0 that add support for Docusaurus 3
